### PR TITLE
add nuxt package

### PR DESCRIPTION
**Pull request by nexxeln**
- create nuxt adapter
- add nuxt example

### CODE REVIEW

**Comment by juliusmarminge** [comment]
> seems to we building locally just fine for me, idk what's wrong

prob to do with the hoisting....

**Comment by nexxeln** [comment]
@juliusmarminge any idea what we should do?

**Comment by juliusmarminge** [comment]
> @juliusmarminge any idea what we should do?

Eeehrm find someone who's used Nuxt in a pnpm monorepo before 😰😰

Im guessing it has to do with the hoisting

**Comment by samydoesit** [comment]
There are two ways to solve this issue: using pnpm hoist patterns, or add the missing dependencies explicitly to the packages that use nuxt.

I prefer the hoist pattern way in this case as described here - https://github.com/nuxt/nuxt/issues/14146#issuecomment-1467427901
```bash
// .npmrc
public-hoist-pattern[]=*vue*
public-hoist-pattern[]=*nuxt*
public-hoist-pattern[]=defu
public-hoist-pattern[]=ufo
```

Created a PR including the changes.

**Comment by juliusmarminge** [comment]
You wanna get this updated @nexxeln ?

**Comment by nexxeln** [comment]
i forgot, will resolve the conflicts and push in a bit

**Review by juliusmarminge — APPROVED** [review]

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
