### PR TITLE
added name of variable that was improperly accessed to error message

### PR DESCRIPTION
**Pull request by tcaputi**
Let me know if this is out of line, but it was tricky to find which variable was being accessed when i first converted to this library.

### CODE REVIEW

**Comment by chungweileong94** [comment]
Looks good! Simple yet useful.

**Comment by juliusmarminge** [comment]
I'm torn on this one, on one hand, the schema is already exposed to the client so the variable names can easily be found if the users dig in to the javascript (See #30). Yet it doesn't feel right just logging it straight out in to the open, I think that should be up to the individual developer using the lib to make that decision?

**Comment by tcaputi** [comment]
So for my part, I made this PR because of my experience migrating my existing app to this library. I have ~25 environment variables in my app and up until now they had all been accessed with just `process.env`. I wanted to switch tot his as soon as i heard about it because my app is already t3 stack and because i value the typesafety on the environment variables.

When i ran the app after setting everything up I just got the `Attempted to access server-side variable on the client` error and i had no clue which of my variables was the problem. In the end I did it with some good old guess and check but this would have at least given me a place to start. Its not bad if im adding a new environment variable, but its just a pain when youre switching over.

I guess in hindsight I could have gone to the browser dev tools and had it pause on exceptions? But I have an error boundary and so i would have had to catch all uncaught exceptions which is pretty noisy.

**Comment by tcaputi** [comment]
Re: security
what if it just only prints the name if NODE_ENV === 'development'?

**Comment by chungweileong94** [comment]
> Re: security
> 
> what if it just only prints the name if NODE_ENV === 'development'?

I think this is okay. Either way, the key will still send to clients, as long as we don't log it.

**Comment by juliusmarminge** [comment]
> I guess in hindsight I could have gone to the browser dev tools and had it pause on exceptions? But I have an error boundary and so i would have had to catch all uncaught exceptions which is pretty noisy.

You get access to the onError override in app level, so you could have just overridden the behavior there. 

Only in dev might be a good middleground.

**Comment by tcaputi** [comment]
> You get access to the onError override in app level, so you could have just overridden the behavior there.

For my edification, where is that? Is that a next thing? a zod thing? a t3-env thing?

**Comment by tcaputi** [comment]
Updated the PR to only print in development

**Comment by tcaputi** [comment]
That would have been good to know about. I didn't think to look under 'Customization' when I was debugging. Maybe this PR could be replaced with a quick doc change.

**Comment by tcaputi** [comment]
not sure what yall want to do with this patch, but it would be nice to either accept or reject it :P

**Review by juliusmarminge — CHANGES_REQUESTED** [review]
Update the docs page too to show the new default

**Comment by tcaputi** [comment]
updated

**Review by juliusmarminge — APPROVED** [review]

**Comment by juliusmarminge** [comment]
Actually, we can't do this. If we put references to `process.env` in by default, things won't work for vite based projects since that uses `import.meta.env`.

So this will have to stay in user land

**Pull request closed without merging**
