### PR TITLE
update nav styling

### PR DESCRIPTION
**Pull request by Willem-Jaap**
-  remove home button, logo acts as navigation to site root sufficiently
- show site name on every screen size
- update main nav button styling, make sure the buttons in sidebar have the same spacing
- fix inconsistent spacing in callout
- only show horizontal scrollbar in code-blocks if there is an overflow
- make outlines on buttons consistent
- fix sidebar spacing

### CODE REVIEW

**Comment by juliusmarminge** [comment]
If we're doing this we should make sure the focus state is the same across the board:

https://user-images.githubusercontent.com/51714798/235437248-f4c62809-e885-4430-b188-037eff5e76ac.mp4

**Comment by Willem-Jaap** [comment]
True, I am willing to fix this when I have the time

**Comment by Willem-Jaap** [comment]
> If we're doing this we should make sure the focus state is the same across the board:

Made some changes to improve consistency

**Review by juliusmarminge — APPROVED** [review]
Looks great! Thanks 🙏🏼

**Pull request merged**
