### PR TITLE
Support for a new validator (joi)

### PR DESCRIPTION
**Pull request by malezjaa**
Support for joi. Code was tested with nextjs and nuxt. 

Example using joi.
```js
export const env = createEnv({
  client: {
    NEXT_PUBLIC_GREETING: Joi.string(),
  },
  server: {
    SECRET: Joi.string(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_GREETING: "hi",
  },
  validator: "joi",
});
```

### CODE REVIEW

**Comment by malezjaa** [comment]
That's right, it won't work using two validators. However, I don't see the point of using two libraries at once.

**Comment by chungweileong94** [comment]
Yeah, that's the point, there might be some structure needs to be made to support different validator.
I don't think it the package should import the validator package directly, or it should at least import from an adapter or some sort, else it won't work unless user install all the validator🤔

There are some discussion in this issue #6, which you can refer to.

**Comment by chungweileong94** [comment]
The fact that the core is importing both `zod` & `joi` at the same time also means that user will have install both packages.

**Comment by malezjaa** [comment]
So, you mean the possibility for the user to import the adapter? Something like unstorage?

**Comment by chungweileong94** [comment]
Never use unstorage before, but something like that.

**Pull request closed without merging**
